# Generated by Django 4.1.1 on 2022-11-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_remove_posts_description_alter_posts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='like',
            new_name='likes',
        ),
    ]
